/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import koneksi.Submit_hadir;
import model.Hadir;
import koneksi.KoneksiDB;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;






/**
 *
 * @author uuser
 */
public class Absensi extends javax.swing.JFrame {

private List<Hadir> ambil   = new ArrayList<>();
private Connection con;
private ResultSet res;
private Statement stat;

    /**
     * Creates new form NewJFrame
     */
    public Absensi() {
        initComponents();
        setLocationRelativeTo(null);
        con = KoneksiDB.getConnect();
        Date now = new Date();
        DateFormat tanggal = DateFormat.getDateInstance(DateFormat.FULL,new Locale("in","ID"));
        jTanggal.setText(tanggal.format(now));               
        jNip.requestFocus();
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH : mm : ss");
        jJam.setText(sdf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new view.background();
        jTanggal = new javax.swing.JLabel();
        jJam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jNip = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jJamMasuk = new javax.swing.JLabel();
        jJabatan = new javax.swing.JLabel();
        jNamaPegawai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTanggal.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jTanggal.setText("Senin 08 Juli 2016");

        jJam.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jJam.setForeground(new java.awt.Color(255, 255, 255));
        jJam.setText("07:00:00");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASUKAN NIP");

        jNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNipActionPerformed(evt);
            }
        });
        jNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNipKeyReleased(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelError.setText("SILAHKAN");

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pegawai");

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jabatan");

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jam Masuk");

        jJamMasuk.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jJamMasuk.setForeground(new java.awt.Color(255, 255, 255));
        jJamMasuk.setText("jLabel7");

        jJabatan.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jJabatan.setForeground(new java.awt.Color(255, 255, 255));
        jJabatan.setText("jLabel6");

        jNamaPegawai.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jNamaPegawai.setForeground(new java.awt.Color(255, 255, 255));
        jNamaPegawai.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ABSENSI PEGAWAI");

        jLabel6.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MFMS BAKERY");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo jadii.jpg"))); // NOI18N

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jJam)
                        .addGap(109, 109, 109)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(47, 47, 47)
                                        .addComponent(jJamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(32, 32, 32)
                                                .addComponent(jNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))))
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNip, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addComponent(jLabelError)
                                .addGap(135, 135, 135))))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jTanggal)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jJam))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNip, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError)
                .addGap(28, 28, 28)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNamaPegawai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jJabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jJamMasuk))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNipActionPerformed

    private void jNipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNipKeyReleased
if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {   String nip, idpegawai;
        boolean status_pegawai, status_hadir;
        
        nip = jNip.getText();
        Hadir hd = new Hadir();
        
        hd.setNIP(nip);
        if(!"".equals(nip)){
          Submit_hadir kehadiran = new Submit_hadir();
            try{
                //cek apakah pegawai ada di tabel pegawai
                status_pegawai = kehadiran.cek_pegawai(hd);
                if(status_pegawai == true){
                    //cek dia harusnya masuk jam berapa
                    Date jam = new Date();
                    SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                    String jam_sekarang = format.format(jam.getTime());
                    
                    ambil = kehadiran.ambil(hd);
                    
                    String data[] = new String[3];
                    for(Hadir h : ambil){
                        data[0] = h.getNama();
                        data[1] = h.getJabatan();
                        data[2] = h.getJamKerja();
                    }
                    Time waktu[] = new Time[4];
                    for(Hadir h : ambil){
                        waktu[0] = h.getMasukStart();
                        waktu[1] = h.getKerjaStart();
                        waktu[2] = h.getKerjaEnd();
                        waktu[3] = h.getKeluarEnd();
                    }
                    
                    Time longjam = Time.valueOf(jam_sekarang);
                    
                    long lj = longjam.getTime();
                    long mm = waktu[0].getTime();
                    long mk = waktu[1].getTime();
                    long sk = waktu[2].getTime();
                    long ks = waktu[3].getTime();
                    //cek apakah pegawai tsb sudah absen masuk atau belum
                    status_hadir = kehadiran.cek_kehadiran(hd);
                    if(status_hadir == true){
                        if(mm < lj && lj < mk ){
                            kehadiran.masuk(hd.getNIP());
                            
                            jNamaPegawai.setText(data[0]);
                            jJabatan.setText(data[1]);
                            jJamMasuk.setText(waktu[1].toString()+" - "+waktu[2].toString());
                            
                            jLabelError.setText("Masuk Berhasil");
                            jNip.setText("");
                            jNip.requestFocus();
                        }else{
                            jLabelError.setText("Anda tidak diperkenankan");
                        }
                    }else if(status_hadir == false) {
                        if(sk < lj && lj < ks == true){
                            kehadiran.keluar(hd.getNIP());
                            
                            jNamaPegawai.setText(data[0]);
                            jJabatan.setText(data[1]);
                            jJamMasuk.setText(waktu[1].toString()+" - "+waktu[2].toString()); 
                            
                            jLabelError.setText("Keluar berhasil");
                            jNip.setText("");
                            jNip.requestFocus();
                        }else{
                            jLabelError.setText("Anda belum diperkenankan");
                        }
                    }
                }else {
                    jLabelError.setText("Pastikan NIP yang anda masukan benar");
                }
            }catch(SQLException ex){
                jLabelError.setText("Kesalahan Database");
            }
        }   jNip.requestFocus();
            jNip.setText("");
    }    
    }//GEN-LAST:event_jNipKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.background background1;
    private javax.swing.JLabel jJabatan;
    private javax.swing.JLabel jJam;
    private javax.swing.JLabel jJamMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jNamaPegawai;
    private javax.swing.JTextField jNip;
    private javax.swing.JLabel jTanggal;
    // End of variables declaration//GEN-END:variables
}
