/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import koneksi.KoneksiDB;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import koneksi.ManKehadiran;
import java.sql.Connection;
import java.util.Date;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import model.ModelFilter;

/**
 *
 * @author uuser
 */
public class DataAbsensi extends javax.swing.JFrame {

    /**
     * Creates new form DataAbsensi
     */
    
    DefaultTableModel tabelkehadiran;
    public void loadTblKehadiran() throws SQLException{
        ManKehadiran mk = new ManKehadiran();
        mk.loadDataKehadiran(tabelkehadiran);
        try {
            int pegawai = mk.getJumlahPegawai();
            label_jumlahpegawai.setText(String.valueOf(pegawai));
            
            int hadir = mk.getTotalHadir();
            int hari = mk.getTotalHari();
            
            double persentase = hadir / hari;
            double persentase2 = persentase / pegawai;
            
            double persentase3 = persentase2 * 100;
            DecimalFormat df = new DecimalFormat("##,##");
                        
            label_presentase_kehadiran.setText(String.valueOf(df.format(persentase3))+" %");
                    
        } catch (SQLException ex) {
            Logger.getLogger(DataAbsensi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public DataAbsensi() throws SQLException {
        initComponents();
        
        tabelkehadiran = new DefaultTableModel();
        
        //menambahkan TableModel ke Tabel
        tabel_kehadiran.setModel(tabelkehadiran);        
        tabelkehadiran.addColumn("Tanggal");
        tabelkehadiran.addColumn("Nama Pegawai");
        tabelkehadiran.addColumn("Jabatan");
        tabelkehadiran.addColumn("Masuk");
        tabelkehadiran.addColumn("Keluar");
        
        loadTblKehadiran();
    }
     
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        background1 = new view.background();
        jLabel3 = new javax.swing.JLabel();
        label_jumlahpegawai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_presentase_kehadiran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kehadiran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUMLAH PEGAWAI");
        background1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 198, -1, -1));

        label_jumlahpegawai.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        label_jumlahpegawai.setForeground(new java.awt.Color(255, 255, 255));
        label_jumlahpegawai.setText("20");
        background1.add(label_jumlahpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 226, -1, 19));

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Orang");
        background1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 256, -1, -1));

        label_presentase_kehadiran.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        label_presentase_kehadiran.setForeground(new java.awt.Color(255, 255, 255));
        label_presentase_kehadiran.setText("100");
        background1.add(label_presentase_kehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 149, -1, 22));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KEHADIRAN");
        background1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 121, -1, -1));

        jLabel6.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATA ABSENSI PEGAWAI");
        background1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        tabel_kehadiran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_kehadiran);

        background1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, 173));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo jadii.jpg"))); // NOI18N
        background1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel10.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MFMS BAKERY");
        background1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataAbsensi().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DataAbsensi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.background background1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_jumlahpegawai;
    private javax.swing.JLabel label_presentase_kehadiran;
    private javax.swing.JTable tabel_kehadiran;
    // End of variables declaration//GEN-END:variables
}
