/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import koneksi.ManGajiPegawai;
import koneksi.ManPegawai;
import model.ModelGaji;
import model.ModelPegawai;
import static view.DataPegawai.cmbJabatan;

/**
 *
 * @author uuser
 */
public class GajiPegawai extends javax.swing.JFrame {
   
DefaultTableModel tabelgaji;
int table;
String Datagaji [] = new String[5];
int row_gaji = 0;

    public void loadTblGajiPegawai() throws SQLException{
        ManGajiPegawai mg = new ManGajiPegawai();
        mg.loadGajiPegawai(tabelgaji, null);
    }
   
    /**
     * Creates new form GajiPegawai
     */
    public GajiPegawai() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        
       
        tabelgaji = new DefaultTableModel();
        //menambahkan TableModel ke Tabel pegawai
        jTabelGajiPegawai.setModel(tabelgaji);        
        tabelgaji.addColumn("ID Pegawai");
        tabelgaji.addColumn("Nama");
        tabelgaji.addColumn("Jabatan");
        tabelgaji.addColumn("Shift");
        tabelgaji.addColumn("Gaji Pegawai");
        
        jTabelGajiPegawai.setModel(tabelgaji);
        
        loadTblGajiPegawai();
        loadGaji();    
    }
   

       public void loadGaji() throws SQLException {
         String id;
        String sql = "SELECT * FROM tbl_gaji";    
        PreparedStatement pst = KoneksiDB.getConnect().prepareStatement(sql);
        ResultSet rs;
        rs = pst.executeQuery(sql);
        
        while(rs.next()){
            jComboGaji.addItem(rs.getString("gaji"));
        }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new view.background();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboJabatan = new javax.swing.JTextField();
        JCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboGaji = new javax.swing.JComboBox();
        jNamaPegawai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonUbah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelGajiPegawai = new javax.swing.JTable();
        cmbShift = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gaji Pegawai");

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Shift");

        JCari.setText("Cari");
        JCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pegawai");

        jComboId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Pegawai");

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jabatan");

        jLabel2.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT. MFMS BAKERY");

        jButtonUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EDIT.png"))); // NOI18N
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jButtonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/DELETE.png"))); // NOI18N
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SAVE.png"))); // NOI18N
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jTabelGajiPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pegawai", "Nama Pegawai", "Jabatan", "Jumlah Jam Kerja", "Gaji Pegawai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabelGajiPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelGajiPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelGajiPegawai);

        cmbShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShiftActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENGGAJIAN KARYAWAN");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cery.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cery.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo jadii.jpg"))); // NOI18N

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9))
                .addGap(57, 57, 57)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addGap(43, 43, 43)
                .addComponent(jLabel10))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jComboId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(JCari))
                    .addComponent(jNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(94, 94, 94)
                .addComponent(jComboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(64, 64, 64)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)))))
                .addGap(29, 29, 29)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCari))
                        .addGap(17, 17, 17)
                        .addComponent(jNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonUbah)))
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHapus)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonSimpan)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
      
            String id_pegawai = jComboId.getText();
            String nama_pegawai = jNamaPegawai.getText();
            String jabatan_pegawai=jComboJabatan.getText();
            String shift_pegawai=cmbShift.getText();
            String gaji = "";
            
            switch(jComboGaji.getSelectedIndex()){
            case 1: gaji = "1500000"; break;
            case 2: gaji = "1500000"; break;
            case 3: gaji = "2500000"; break;
            case 4: gaji = "2500000"; break;
            case 5: gaji = "2500000"; break;
            case 6: gaji = "3500000"; break;
            case 7: gaji = "3500000"; break;
            case 8: gaji = "3500000"; break;
            default:gaji = "";break;
        }
            
            ModelGaji mogj = new ModelGaji();
            mogj.setIdpegawai(id_pegawai);
            mogj.setNama(nama_pegawai);
            mogj.setJabatan(jabatan_pegawai);
            mogj.setShift(shift_pegawai);
            mogj.setGaji(gaji);
        
            if(id_pegawai.equals("") | nama_pegawai.equals("") | jabatan_pegawai.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Harap isi semua field");
        }
        else{    
            try {
            ManGajiPegawai mang = new ManGajiPegawai();
            
            if(mang.cekGajiPegawai(mogj)== true){
            int konfirmasiUbah = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin akan mengubah data gaji Pegawai: \n NIP : "+mogj.getIdpegawai()+" \n Nama : "+mogj.getNama()+" \n Gaji : "+mogj.getGaji()+ "\n Yakin Ubah Data Gaji Pegawai ? ","Data Gaji Pegawai Berhasil Diubah", JOptionPane.YES_NO_OPTION);
                    //jika user klik yes
                    if(konfirmasiUbah == JOptionPane.YES_OPTION){
                        //lakukan mekanisme update informasi kedatabase 
                        try{                            
                            mang.updateGajiPegawai(mogj);
                             
                            JOptionPane.showMessageDialog(rootPane, "Data Gaji Berhasil Diubah", "Data berhasil Diubah",JOptionPane.INFORMATION_MESSAGE);
                        }
                        catch(SQLException ex){
                            JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan","Kesalahan Menyimpan Data",JOptionPane.ERROR_MESSAGE);
                            Logger.getLogger(GajiPegawai.class.getName()).log(Level.SEVERE, null, ex);
                        }   
           }}}catch(SQLException e){
                   JOptionPane.showMessageDialog(rootPane, "ID Pegawai Tidak Ditemukan");
                   }finally{
                            try {
                                loadTblGajiPegawai();

                                jComboId.setEnabled(false);
                                jComboId.setText("");
                                
                                jNamaPegawai.setEnabled(false);
                                jNamaPegawai.setText("");

                                jComboJabatan.setEnabled(false);
                                jComboJabatan.setText("");
                                
                                cmbShift.setEnabled(false);
                                cmbShift.setText("");
                                
                                jComboGaji.setEnabled(false);
                                jComboGaji.setSelectedItem(0);

                            } catch (SQLException ex) {
                                
                                Logger.getLogger(GajiPegawai.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
            }
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
 int i = jTabelGajiPegawai.getSelectedRow();
        if(i== -1){
            return;
        }
        String nip = (String) jTabelGajiPegawai.getValueAt(i, 0);
        String nama = (String) jTabelGajiPegawai.getValueAt(i, 1);
        
        ModelGaji mogj = new ModelGaji();
        mogj.setIdpegawai(nip);
        mogj.setNama(nama);

        int konfirmasiHapus = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin akan menghapus data pegawai "
            + "dengan \n NIP "+nip+", yang bernama "+nama+"? ", "Hapus Pegawai", JOptionPane.YES_NO_OPTION);
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            try{
                ManGajiPegawai mang = new ManGajiPegawai();
                mang.hapusGajiPegawai(mogj);
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Dihapus", "Berhasil Menghapus Data",JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Menghapus Data","Kesalahan Menghapus Data",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DataPegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    loadTblGajiPegawai();
                    
                    jComboId.setEnabled(false);
                    jComboId.setText("");

                    jNamaPegawai.setEnabled(false);
                    jNamaPegawai.setText("");

                    jComboJabatan.setEnabled(false);
                    jComboJabatan.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(DataPegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
   
       try {
            Connection Vkon = KoneksiDB.getConnect();
            Statement Statgaji = Vkon.createStatement();
            String SQL_gaji = "INSERT INTO tbl_gajipegawai VALUES('"+jComboId.getText()+"',"
                    + "'"+jNamaPegawai.getText()+"',"
                    + "'"+jComboJabatan.getText()+"',"
                    + "'"+cmbShift.getText()+"',"
                    + "'"+jComboGaji.getSelectedItem()+"')";
            Statgaji.execute(SQL_gaji);
            
            Datagaji[0]=jComboId.getText();
            Datagaji[1]=jNamaPegawai.getText();
            Datagaji[2]=jComboJabatan.getText();
            Datagaji[3]=cmbShift.getText();
            Datagaji[4]=(String) jComboGaji.getSelectedItem();
            
            
            tabelgaji.insertRow(0, Datagaji);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
      
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jComboIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboIdActionPerformed

    private void JCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCariActionPerformed
        // TODO add your handling code here:
    VCariPegawai tampilpegawai = new VCariPegawai();
    
    //membuat tampilan form tengah
    tampilpegawai.setLocationRelativeTo(this);
    
    tampilpegawai.setVisible(true);
    tampilpegawai.edcari.setText("");
    tampilpegawai.edcari.requestFocus();
       
    }//GEN-LAST:event_JCariActionPerformed

    private void jTabelGajiPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelGajiPegawaiMouseClicked
 int i = jTabelGajiPegawai.getSelectedRow();
        if(i== -1){
            JOptionPane.showMessageDialog(rootPane, "Tidak ada data pegawai yang dipilih");
        }

        jComboId.setEnabled(false);
        jNamaPegawai.setEnabled(false);
        jComboJabatan.setEnabled(false);
        cmbShift.setEnabled(false);
        jComboGaji.setEnabled(true);

        String nip = (String) jTabelGajiPegawai.getValueAt(i, 0);
        jComboId.setText(nip);

        String nama = (String) jTabelGajiPegawai.getValueAt(i, 1);
        jNamaPegawai.setText(nama);

        String jabatan = (String) jTabelGajiPegawai.getValueAt(i, 2);
        jComboJabatan.setText(jabatan);
        
        String shift = (String) jTabelGajiPegawai.getValueAt(i, 3);
        cmbShift.setText(shift);
        String gaji = (String) jTabelGajiPegawai.getValueAt(i, 3);
        jComboGaji.setSelectedItem(gaji);
        
    }//GEN-LAST:event_jTabelGajiPegawaiMouseClicked

    private void cmbShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbShiftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GajiPegawai().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GajiPegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JCari;
    private view.background background1;
    public static javax.swing.JTextField cmbShift;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JComboBox jComboGaji;
    public static javax.swing.JTextField jComboId;
    public static javax.swing.JTextField jComboJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jNamaPegawai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelGajiPegawai;
    // End of variables declaration//GEN-END:variables

    private void dataTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
