/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.KoneksiDB;
import koneksi.ManLogin;
import model.ModelLogin;

/**
 *
 * @author uuser
 */
public class Login extends javax.swing.JFrame {
private Connection con;
private ResultSet res;
private Statement stat;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        con = KoneksiDB.getConnect();      
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLogin1 = new view.bgLogin();
        bgLogin2 = new view.bgLogin();
        jTombolKeluar = new javax.swing.JButton();
        jTombolLogin = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jTextUserName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(240, 106, 194));

        jTombolKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/KELUARpng.png"))); // NOI18N
        jTombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTombolKeluarActionPerformed(evt);
            }
        });

        jTombolLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MASUKpng.png"))); // NOI18N
        jTombolLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTombolLoginActionPerformed(evt);
            }
        });

        jPassword.setText("jPasswordField1");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });

        jTextUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserNameActionPerformed(evt);
            }
        });
        jTextUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextUserNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout bgLogin2Layout = new javax.swing.GroupLayout(bgLogin2);
        bgLogin2.setLayout(bgLogin2Layout);
        bgLogin2Layout.setHorizontalGroup(
            bgLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLogin2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jTombolLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLogin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextUserName)
                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        bgLogin2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPassword, jTextUserName});

        bgLogin2Layout.setVerticalGroup(
            bgLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLogin2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTombolKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTombolLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        bgLogin2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPassword, jTextUserName});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserNameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserNameActionPerformed

    private void jTextUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserNameFocusGained
        jTextUserName.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserNameFocusGained

    private void jTextUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserNameFocusLost
        if(jTextUserName.equals("")){
            jTextUserName.setText("username");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserNameFocusLost

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        jPassword.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        if(jPassword.equals("")){
            jPassword.setText("username");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFocusLost

    private void jTombolLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTombolLoginActionPerformed
       try { String status;
            String url="jdbc:mysql://localhost:3306/db_penggajian";
            String user="root";
            String password="08071996";
            
            java.sql.Connection con = (java.sql.Connection) KoneksiDB.getConnect();
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet res = stat.executeQuery
        ("select * from tbl_login where username= '"+jTextUserName.getText()+""
                + "' AND password= '"+jPassword.getText()+"'");
            
            if(res.next()){
                status = res.getString("status");
                if("admin".equals(status)){
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "BERHASIL LOGIN SEBAGAI ADMIN");
                    ViewAdmin va = new ViewAdmin();
                    va.setVisible(true);
                }else{
                    this.dispose();
                    JOptionPane.showMessageDialog(null,"BERHASIL LOGIN SEBAGAI USER");
                    Absensi a = new Absensi();
                    a.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"username dan password tidak tersedia");
            }
            }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"terjadi kesalahan");
        }
    }//GEN-LAST:event_jTombolLoginActionPerformed

    private void jTombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTombolKeluarActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_jTombolKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.bgLogin bgLogin1;
    private view.bgLogin bgLogin2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUserName;
    private javax.swing.JButton jTombolKeluar;
    private javax.swing.JButton jTombolLogin;
    // End of variables declaration//GEN-END:variables

    private void ifelse(boolean equals) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
