/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import koneksi.ManPegawai;
import model.ModelPegawai;
import java.util.ArrayList;

/**
 *
 * @author uuser
 */
public class VCariPegawai extends javax.swing.JFrame {
    
   List<ModelPegawai> record = new ArrayList<>();
   
   ManPegawai pnbservice;
   
   int row;
   
   void panggildata(){
       try {
           record = pnbservice.cekPegawai();
       } catch (Exception e) {
       }
   }
   
   void isitabel(){
       Object data[][] = new Object[record.size()][4];
       int x = 0;
       for(ModelPegawai pegawai : record){
           
           data[x][0] = pegawai.getIdpegawai();
           data[x][1] = pegawai.getNama();
           data[x][2] = pegawai.getJabatan();
           data[x][3] = pegawai.getShift();
           
           x++;
       }
       
       String judul[]= {"idpegawai","nama","jabatan","jamkerja"};
      jtblpegawai.setModel(new DefaultTableModel(data,judul));
   }
   
   void refreshdata(){
       panggildata();
       isitabel();
   }

    /**
     * Creates new form VCariPegawai
     */
    public VCariPegawai() {
        initComponents();
        
        pnbservice = new ManPegawai();
        
        this.refreshdata();
        this.panggildata();
        this.isitabel();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        background1 = new view.background();
        jLabel1 = new javax.swing.JLabel();
        edcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblpegawai = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masukkan Kode Pegawai");

        edcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edcariActionPerformed(evt);
            }
        });
        edcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edcariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edcariKeyReleased(evt);
            }
        });

        jtblpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblpegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblpegawai);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(edcari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edcari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblpegawaiMouseClicked
        // TODO add your handling code here:
        if (jtblpegawai.getSelectedColumnCount()==1) {
            
            int rows = jtblpegawai.getSelectedRow();
            
            GajiPegawai.jComboId.setText(jtblpegawai.getValueAt(rows, 0).toString());
            GajiPegawai.jNamaPegawai.setText(jtblpegawai.getValueAt(rows, 1).toString());
            GajiPegawai.jComboJabatan.setText(jtblpegawai.getValueAt(rows, 2).toString());
            GajiPegawai.cmbShift.setText(jtblpegawai.getValueAt(rows, 3).toString());

            GajiPegawai.jComboId.requestFocus();
            dispose();
        }
    }//GEN-LAST:event_jtblpegawaiMouseClicked

    private void edcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edcariActionPerformed

    private void edcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edcariKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edcariKeyReleased

    private void edcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edcariKeyPressed
        // TODO add your handling code here:
 DefaultTableModel tampil_tbl = new DefaultTableModel();
 tampil_tbl.addColumn("ID PEGAWAI");
 tampil_tbl.addColumn("Nama Pegawai");
 tampil_tbl.addColumn("Jabatan");
 tampil_tbl.addColumn("Jam Kerja");
 
        try { 
            java.sql.Connection ambil = new KoneksiDB().getConnect();
            java.sql.Statement stmt = ambil.createStatement();
            
        String sql = "SELECT * FROM tbl_pegawai where idpegawai like'%"+edcari.getText() +"%'";
        java.sql.ResultSet rs = stmt.executeQuery(sql);
        
        while (rs.next()) {
            
            tampil_tbl.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)
                });
          }
        
           jtblpegawai.setModel(tampil_tbl); 
       
        } catch (Exception e) {
        }
    }//GEN-LAST:event_edcariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCariPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCariPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCariPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCariPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCariPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.background background1;
    public static javax.swing.JTextField edcari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtblpegawai;
    // End of variables declaration//GEN-END:variables
}
